#将静态内容部署到GitHub页面的简单工作流程
名称:将静态内容部署到Pages

开启:
#在针对默认分支的推送中运行
推送::
分支::

#允许您从"操作"选项卡手动运行此工作流
  workflow_dispatch::

#设置GITHUB_TOKEN的权限以允许部署到GitHub页面
权限::
身份标记:写入
身份标记:写入
身份标记:写入

#只允许一次并发部署，跳过在正在进行的运行和最近排队的运行之间的排队。
#但是，请不要取消正在进行的运行，因为我们希望这些生产部署能够完成。
并发性::
组:"页面""页面"
组:

组:"页面":
# 单次部署作业，因为我们刚刚部署
部署::
环境::
步骤:
步骤
运行在:ubuntu-latest
步骤运行在:ubuntu-latest步骤运行在:ubuntu-latest运行在:ubuntu-latest名称:github-pages:
-名称:退房
-名称:上传工件
-名称:设置页
用途:操作/配置页面@v5
-名称:上传工件
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
